Motor_arduino_python.v1
pfe-rs/lk-s-2024-ball-on-wheel pull request #11
Opened 2024-07-23 13:50 UTC by budjavko

Slanje pwm-a iz pythona u arduino, treba da se sredi

2024-07-23 15:17 UTC, djokjulapfe approved these changes
lgtm

2024-07-23 16:19 UTC, djokjulapfe requested changes
Proverite ovo malo bolje. Nema smisla da init prima napon kao argument a `set_voltage` prima arduino.

2024-07-23 16:19 UTC, djokjulapfe commented on motor.py
> +    def salji_napon(self,arduino):
Zar ne treba argument da bude napon?

2024-07-23 17:00 UTC, budjavko commented on motor.py
> +    def salji_napon(self,arduino):
Moze ovako?

2024-07-23 19:40 UTC, lenkajj commented on motor.py
> +    motor.salji_napon(napon,arduino)
Stavi u `if __main__ ==...`

2024-07-24 07:17 UTC, djokjulapfe approved these changes
lgtm

2024-07-24 07:17 UTC, djokjulapfe commented on motor.py
> +    motor.salji_napon(napon,arduino) """
Stavite ovo u `if __main__ == ...`

2024-07-24 13:34 UTC, merged